#config.yml

ng.app.name: ng-phalcon

default.lang: en

database:
  host: localhost
  username: root
  password:
  dbname: phalcon

view:
  compiledPath: /tmp/app/
  compiledExtension: .compiled
  compiledSeparator: '%%'
  stat: true
  compileAlways: true
  
logger:
  web:
    level: 7  
    adapters:
      file: '/tmp/app.log'
  console:  
    level: 7  
    adapters:
      file: '/tmp/console_app.log'