#modules.yml
#moduleName:
#  className: moduleName\Module
#  path: modules/moduleName/Module.php

ngEvent:
  className: mirolabs\phalcon\modules\ngEvent\Module
  path: vendor/mirolabs/ng-event/src/Module.php

